import requests
from bs4 import BeautifulSoup

cities = {
    "GILROY": "623",
    "LODI": "622",
    "FAIRFIELD": "621",
    "INDIO": "578",
    "GARBERVILLE": "627",
    "REDLANDS": "626",
    "CARMICHAEL": "625",
    "OAKLAND COLISEUM": "604",
    "PORTERVILLE": "573",
    "WEAVERVILLE": "572",
    "VICTORVILLE": "629",
    "AUBURN": "570",
    "RIDGECREST": "577",
    "BELL GARDENS": "576",
    "ARVIN": "661",
    "PASO ROBLES": "574",
    "PITTSBURG": "592",
    "TORRANCE": "608",
    "PARADISE": "601",
    "WILLOWS": "571",
    "LOS BANOS": "650",
    "TULARE": "594",
    "VALLEJO": "554",
    "GRASS VALLEY": "541",
    "PALMDALE": "690",
    "COALINGA": "603",
    "ROSEVILLE": "543",
    "HAYWARD": "579",
    "SACRAMENTO SOUTH": "602",
    "RIVERSIDE EAST": "656",
    "FONTANA": "657",
    "NAPA": "540",
    "FOLSOM": "655",
    "HOLLISTER": "546",
    "SAN LUIS OBISPO": "547",
    "HOLLYWOOD": "508",
    "PASADENA": "509",
    "SAN DIEGO": "506",
    "HOLLYWOOD WEST": "652",
    "OAKLAND CLAREMONT": "504",
    "FRESNO": "505",
    "LOS ANGELES": "502",
    "SAN FRANCISCO": "503",
    "MANTECA": "658",
    "PALM SPRINGS": "659",
    "SAN ANDREAS": "568",
    "PLEASANTON": "631",
    "SANTA CLARA": "632",
    "COSTA MESA": "628",
    "PETALUMA": "634",
    "BAKERSFIELD SW": "679",
    "OXNARD": "636",
    "WINNETKA": "637",
    "SANTA ANA": "542",
    "MOUNT SHASTA": "639",
    "POWAY": "676",
    "RIVERSIDE": "545",
    "COLUSA": "564",
    "HANFORD": "565",
    "MARIPOSA": "566",
    "NEWHALL": "662",
    "WEST COVINA": "618",
    "SANTA ROSA": "555",
    "TAFT": "575",
    "WHITTIER": "591",
    "LONG BEACH": "507",
    "EL CAJON": "669",
    "SHAFTER": "660",
    "REDWOOD CITY": "548",
    "WESTMINSTER": "611",
    "ROCKLIN": "673",
    "SANTA BARBARA": "549",
    "SEASIDE": "567",
    "SANTA MARIA": "563",
    "SAN PEDRO": "619",
    "VENTURA": "560",
    "MERCED": "536",
    "UKIAH": "535",
    "CORTE MADERA": "534",
    "MADERA": "533",
    "POMONA": "532",
    "SUSANVILLE": "531",
    "LAKEPORT": "530",
    "SANTA TERESA": "668",
    "REDDING": "551",
    "QUINCY": "544",
    "SALINAS": "539",
    "SOUTH LAKE TAHOE": "538",
    "LAGUNA HILLS": "605",
    "FORT BRAGG": "590",
    "FULLERTON": "607",
    "BELLFLOWER": "606",
    "LANCASTER": "595",
    "RED BLUFF": "558",
    "BRAWLEY": "597",
    "OCEANSIDE": "596",
    "DALY CITY": "599",
    "DAVIS": "598",
    "MODESTO": "557",
    "EL CERRITO": "556",
    "HAWTHORNE": "609",
    "CAPITOLA": "550",
    "TULELAKE": "553",
    "YREKA": "552",
    "REEDLEY": "633",
    "SAN YSIDRO": "677",
    "WALNUT CREEK": "624",
    "SONORA": "569",
    "HEMET": "635",
    "GOLETA": "670",
    "SAN DIEGO CLAIREMONT": "519",
    "VISALIA": "559",
    "TURLOCK": "649",
    "YUBA CITY": "562",
    "CRESCENT CITY": "524",
    "PLACERVILLE": "525",
    "EUREKA": "526",
    "EL CENTRO": "527",
    "CHICO": "520",
    "JACKSON": "521",
    "OROVILLE": "522",
    "CONCORD": "523",
    "SAN MARCOS": "620",
    "SACRAMENTO": "501",
    "BLYTHE": "528",
    "BAKERSFIELD": "529",
    "NORCO": "586",
    "ARLETA": "587",
    "NEEDLES": "584",
    "BISHOP": "585",
    "BARSTOW": "582",
    "WATSONVILLE": "583",
    "CLOVIS": "580",
    "COMPTON": "581",
    "RANCHO CUCAMONGA": "612",
    "CHULA VISTA": "613",
    "INGLEWOOD": "610",
    "STOCKTON": "517",
    "SANTA MONICA": "616",
    "LINCOLN PARK": "617",
    "VACAVILLE": "588",
    "DELANO": "615",
    "MONTEBELLO": "511",
    "WOODLAND": "561",
    "TEMECULA": "672",
    "SAN CLEMENTE": "648",
    "LOMPOC": "589",
    "TRUCKEE": "513",
    "TWENTYNINE PALMS": "638",
    "SAN BERNARDINO": "512",
    "SANTA PAULA": "630",
    "SAN MATEO": "593",
    "SIMI VALLEY": "680",
    "BANNING": "641",
    "LOS GATOS": "640",
    "FALL RIVER MILLS": "643",
    "TRACY": "642",
    "THOUSAND OAKS": "663",
    "FREMONT": "644",
    "KING CITY": "647",
    "FRESNO NORTH": "646",
    "EL MONTE": "685",
    "GLENDALE": "510",
    "LAKE ISABELLA": "687",
    "NOVATO": "686",
    "VAN NUYS": "515",
    "CULVER CITY": "514",
    "PALM DESERT": "683",
    "SAN JOSE": "516"
}

def get_nearby_locations(zip):
    loc_url = "http://local.dmv.org/dmv-office-locations.php?q_local={}&localSearchSubmit=".format(zip)
    resp = requests.get(loc_url)
    html = BeautifulSoup(resp.text)
    locations = html.body.find_all('li', attrs={'class': 'branchListItem'})
    locations = [str(location.get('url').split('/')[3].replace('-', ' ')).upper() for location in locations]
    return locations


def get_date(officeId):
    url = 'https://www.dmv.ca.gov/wasapp/foa/findOfficeVisit.do'
    payload = {
        'officeId': officeId,
        'numberItems': 1,
        'taskDL': True,
        'firstName': 'first',
        'lastName': 'last',
        'telArea': '219',
        'telPrefix': '456',
        'telSuffix': '9036',
        'resetCheckFields': True
    }

    r = requests.post(url, data=payload)
    if r.status_code == 200:
        html = BeautifulSoup(r.text)
        date = html.body.find_all('p', attrs={'class': 'alert'})[1].text
        return str(date)
    else:
        print 'error ', r.status_code


zip = '94103'
locations = get_nearby_locations(zip)
officeIds = {location: cities.get(location) for location in locations}
dates = {location: get_date(officeId) for location, officeId in officeIds.iteritems() if officeId}
for location, date in dates.iteritems():
    print location, ': ', date
